---
# systemctl enable php-fpm --now
- name: Start php-fpm service Debian
  ansible.builtin.systemd:
    name: "php{{ php_version }}-fpm"
    state: restarted
    enabled: yes
  when: ansible_os_family == "Debian"

# systemctl enable php-fpm --now
- name: Start php-fpm service RedHat
  ansible.builtin.systemd:
    name: "php-fpm"
    state: restarted
    enabled: yes
  when: ansible_os_family == "RedHat"