---
# systemctl enable nftables --now
- name: Start NFTables Service
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: yes

# targetcli saveconfig
- name: targetcli saveconfig
  ansible.builtin.command: targetcli saveconfig